### ISSUE TITLE
No SKMotionSensing.h header file in built framework.

### ISSUE THREAD

**Issue by itsprabin** [SensingKit/SensingKit-iOS#1]
Hello there,
I built the SENSINGKIT framework as per the steps provided. But the built framework has no SKMotionSensing.h header file. I guess we can't use motion sensor and accelerometer without that particular header file.

Also I am not being able to access the SKMotionSensing.h file. 
Best Regards,
Prabin

**Comment by minoskt** [comment]
Hi @itsprabin 

We updated the library recently in order to make it compatible to the Android's API. Unfortunately porting Motion / Orientation sensing is not ready just yet (even though we should have mention that in the README file).

I am working on it right now, should be ready in the next 3-4 days.
Thank you for the feedback and excuse me for any inconvenience.

Regards
Minos

**Comment by itsprabin** [comment]
Hi Minos,
Good to hear from you. I will be waiting for the updated framework. Its a great library to work on. Thank you very much.

Best Regards,
Prabin

**Comment by minoskt** [comment]
Hi Prabin

I just pushed an update with support to the following sensors:
- Accelerometer
- Gyroscope
- Magnetometer
- DeviceMotion (for Gravity, Linear Acceleration etc)
- Activity

Please let me know if that works for you.

Best regards
Minos
